language: ruby
cache: bundler
sudo: false
rvm:
  - 2.6.3

notifications:
  email:
    - jcoyne@justincoyne.com
    - casey@softwareforgood.com

before_script:
  - cd src/
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - bundle install

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

bundler_args: --without development debug
